CREATE TABLE CONTA (
   ID INT AUTO_INCREMENT PRIMARY KEY, 
   NOME_CLIENTE VARCHAR, 
   SALDO FLOAT
);

INSERT INTO CONTA (ID, NOME_CLIENTE, SALDO)
VALUES (1,'Vitor Faro', 2001.30);

INSERT INTO CONTA (ID, NOME_CLIENTE, SALDO)
VALUES (2, 'Savio Franca', 3500.55);

INSERT INTO CONTA (ID, NOME_CLIENTE, SALDO)
VALUES (3, 'Cleber Silva', 400.60);

INSERT INTO CONTA (ID, NOME_CLIENTE, SALDO)
VALUES (4, 'Simone Lourenço', 1050.33);

INSERT INTO CONTA (ID, NOME_CLIENTE, SALDO)
VALUES (5, 'Luna Maia', 200.00);

INSERT INTO CONTA (ID, NOME_CLIENTE, SALDO)
VALUES (6, 'Helena Dutra', 5500.00);